#!/bin/bash
# chkconfig: 345 75 25
# description: Tuna Forward Service

PID_FILE=/var/run/tuna-forward.pid
case "$1" in
	start)
		/usr/java/default/bin/java -Xms16m -Xmx32m -cp /usr/local/tuna/lib/tuna-tools.jar com.xqbase.tuna.cli.Forward 80 tuna.xqbase.com 443 -s &
		echo $! > $PID_FILE
		;;
	stop)
		read pid < $PID_FILE
		kill $pid
		rm $PID_FILE
		;;
esac