#!/bin/bash
# chkconfig: 345 75 25
# description: Tuna Mux Guest Service

PID_FILE=/var/run/tuna-mux-guest.pid
case "$1" in
	start)
		/usr/share/java/bin/java -Xms16m -Xmx32m -cp /usr/local/tuna/lib/tuna-tools.jar com.xqbase.tuna.cli.MuxGuest 80 localhost 80 tuna.xqbase.com 8341 &
		echo $! > $PID_FILE
		;;
	stop)
		read pid < $PID_FILE
		kill $pid
		rm $PID_FILE
		;;
esac