#!/bin/bash
# chkconfig: 345 75 25
# description: Tuna Mux Host Service

PID_FILE=/var/run/tuna-mux-host.pid
case "$1" in
	start)
		/usr/share/java/bin/java -Xms16m -Xmx32m -cp /usr/local/tuna/lib/tuna-tools.jar com.xqbase.tuna.cli.MuxHost 8341 &
		echo $! > $PID_FILE
		;;
	stop)
		read pid < $PID_FILE
		kill $pid
		rm $PID_FILE
		;;
esac