#!/bin/bash
# chkconfig: 345 75 25
# description: Tuna Proxy

PID_FILE=/var/run/tuna-proxy.pid
case "$1" in
        start)
                java -jar /usr/local/tuna/lib/tuna-proxy.jar &
                echo $! > $PID_FILE
                ;;
        stop)
                read pid < $PID_FILE
                kill $pid
                rm $PID_FILE
                ;;
esac